import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { readFileSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv.includes("--production");
const watch = process.argv.includes("--watch");

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  // Use mainFields to prefer browser versions of packages
  mainFields: ["browser", "module", "main"],
  // Conditions to resolve package.json conditional exports
  conditions: ["browser", "import", "default"],
  // Handle JSX with React automatic runtime
  jsx: "automatic",
  // Platform is browser since we target Obsidian's Electron renderer
  // and want browser entries for @likec4/language-services
  platform: "browser",
  // Define globals that may be expected
  define: {
    "process.env.NODE_ENV": prod ? '"production"' : '"development"',
    global: "globalThis",
  },
  // Handle CSS by bundling it
  loader: {
    ".css": "css",
    ".wasm": "binary",
  },
  // Allow importing .css in JS
  plugins: [
    {
      name: "css-import-as-text",
      setup(build) {
        // Redirect CSS imports to be loaded as text for injection
        build.onResolve({ filter: /\.css$/ }, (args) => {
          if (args.kind === "import-statement" || args.kind === "require-call") {
            return {
              path: args.path,
              namespace: "css-text",
              pluginData: { resolveDir: args.resolveDir },
            };
          }
        });
        build.onLoad({ filter: /.*/, namespace: "css-text" }, async (args) => {
          const { resolve } = await import("path");
          const { existsSync } = await import("fs");

          // Try to resolve the CSS file
          let fullPath = args.path;
          if (!fullPath.startsWith("/")) {
            fullPath = resolve(args.pluginData.resolveDir, args.path);
          }

          if (existsSync(fullPath)) {
            const css = readFileSync(fullPath, "utf8");
            return {
              contents: `/* CSS from ${args.path} */`,
              loader: "js",
            };
          }

          return { contents: "", loader: "js" };
        });
      },
    },
  ],
});

if (watch) {
  await context.watch();
} else {
  await context.rebuild();
  process.exit(0);
}
